# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f9d0a1b944f3c65a7239f288c1e17a7"
application_url = "https://github.com/Duxly/store-and-style-woerden-customisation"
embedded = false
name = "Duxly Connection Style Woerden"

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_orders,write_orders,write_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://github.com/Duxly/store-and-style-woerden-customisation/auth/callback"
]
