AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Shopify App Template - Serverless application for Shopify OAuth and credential storage

Parameters:
  ShopifyApiKey:
    Type: String
    Description: Shopify API Key (Client ID)
    NoEcho: false

  ShopifyApiSecret:
    Type: String
    Description: Shopify API Secret
    NoEcho: true

  ParameterStorePrefix:
    Type: String
    Description: Parameter Store prefix for storing credentials
    Default: '/shopify/clients'

  FrontendUrl:
    Type: String
    Description: Frontend URL (set after first deployment)
    Default: ''

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        SHOPIFY_API_KEY: !Ref ShopifyApiKey
        SHOPIFY_API_SECRET: !Ref ShopifyApiSecret
        PARAMETER_STORE_PREFIX: !Ref ParameterStorePrefix

Resources:
  # API Gateway
  ShopifyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Function - OAuth Initiation
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: auth.handler
      Events:
        AuthEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ShopifyApi
            Path: /auth
            Method: GET

  # Lambda Function - OAuth Callback
  CallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: callback.handler
      Environment:
        Variables:
          FRONTEND_URL: !Ref FrontendUrl
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:GetParameter
                - ssm:DeleteParameter
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*'
      Events:
        CallbackEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ShopifyApi
            Path: /callback
            Method: GET

  # Lambda Function - App Proxy
  ProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: proxy.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*'
      Events:
        ProxyEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ShopifyApi
            Path: /proxy
            Method: POST

  # Lambda Function - GDPR Compliance Webhooks
  GdprFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: gdpr.handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:DeleteParameter
                - ssm:DescribeParameters
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterStorePrefix}/*'
            - Effect: Allow
              Action:
                - ssm:DescribeParameters
              Resource: '*'
      Events:
        GdprCustomersDataRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ShopifyApi
            Path: /webhooks/gdpr/customers_data_request
            Method: POST
        GdprCustomersRedact:
          Type: Api
          Properties:
            RestApiId: !Ref ShopifyApi
            Path: /webhooks/gdpr/customers_redact
            Method: POST
        GdprShopRedact:
          Type: Api
          Properties:
            RestApiId: !Ref ShopifyApi
            Path: /webhooks/gdpr/shop_redact
            Method: POST

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # S3 Bucket Policy for Public Read
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket.Arn}/*'

  # CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - DomainName: !GetAtt FrontendBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${ShopifyApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${AWS::StackName}-ApiUrl'

  FrontendUrl:
    Description: CloudFront Distribution URL
    Value: !Sub 'https://${FrontendDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-FrontendUrl'

  FrontendBucketName:
    Description: S3 Bucket for Frontend
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucket'

  AuthFunctionArn:
    Description: Auth Lambda Function ARN
    Value: !GetAtt AuthFunction.Arn

  CallbackFunctionArn:
    Description: Callback Lambda Function ARN
    Value: !GetAtt CallbackFunction.Arn

  ProxyFunctionArn:
    Description: Proxy Lambda Function ARN
    Value: !GetAtt ProxyFunction.Arn

  GdprFunctionArn:
    Description: GDPR Compliance Lambda Function ARN
    Value: !GetAtt GdprFunction.Arn

  GdprWebhookUrls:
    Description: GDPR Webhook URLs for Shopify Partner Dashboard
    Value: !Sub |
      customers/data_request: https://${ShopifyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhooks/gdpr/customers_data_request
      customers/redact: https://${ShopifyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhooks/gdpr/customers_redact
      shop/redact: https://${ShopifyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhooks/gdpr/shop_redact
